# Generated by Django 3.2 on 2024-08-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_onetimepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='otp',
            field=models.IntegerField(unique=True),
        ),
    ]
