# Generated by Django 3.2 on 2024-08-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(default='ajayyo3337@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
