# Generated by Django 3.2 on 2024-08-16 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_data', '0001_initial'),
        ('medical_resources', '0001_initial'),
        ('patient', '0001_initial'),
        ('doctors', '0003_doctor_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=100, unique=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_data.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('general', 'General'), ('semi_private', 'Semi-Private'), ('private', 'Private'), ('icu', 'ICU')], max_length=20)),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_data.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pharmacy_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_section.pharmacybill')),
                ('pharmacy_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_resources.pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='items',
            field=models.ManyToManyField(through='bill_section.PharmacyBillItem', to='medical_resources.Pharmacy'),
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.CreateModel(
            name='OperationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(max_length=100, unique=True)),
                ('operation_type', models.CharField(max_length=255)),
                ('operation_date', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_data.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='BedRestCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_id', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_data.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_section.room')),
            ],
        ),
    ]
