# Generated by Django 3.2 on 2024-08-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('DOC', 'Doctor'), ('PTNT', 'patient'), ('EMP', 'Employee'), ('APNT', 'Appointment'), ('STY', 'STAY'), ('OPRT', 'Operation'), ('BL', 'BILL')], max_length=4)),
                ('number', models.CharField(max_length=6)),
            ],
        ),
    ]
