# Generated by Django 3.2 on 2024-08-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencenumber',
            name='section',
            field=models.CharField(choices=[('DOC', 'Doctor'), ('PTNT', 'patient'), ('EMP', 'Employee'), ('APNT', 'Appointment'), ('STY', 'STAY'), ('OPRT', 'Operation'), ('BL', 'BILL'), ('MDC', 'Medicine'), ('EQP', 'Equipment')], max_length=4),
        ),
    ]
