# Generated by Django 3.2 on 2024-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20240812_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(default='CH012', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
